TEXTURES
empty, 
bot_dirt1, 
bot_grass1,░
acre_empty, 
acre_wheat_sown, 
acre_wheat_growing,░
acre_wheat_mature,▒
acre_wheat_ripe,▓
acre_carot,❦
forage_mushroom1,♣
forage_mushroom2,♧
forage_acorn,❧
npc_person,♟
obj_stone1,˙
obj_stone2,·
obj_stone3,.
obj_stone4,⌃
obj_stone5,•
obj_grass1,`
obj_grass2,'
obj_grass3,¨
obj_shaft1,/
obj_shaft2,\
plant_flower1,⚘
plant_flower2,❀
plant_flower3,✿
plant_bush1,✾
struct_chimney1,░
struct_roof1,▰
struct_roof2,▱
struct_wall1,▓
struct_beam_vert1,╋
struct_beam_vert2,|
struct_beam_horz1,━
struct_beam_diagonal,/
struct_floor1,║
struct_door1,▯
struct_window1,⊞
struct_stairs1,▤
tree_oak_top,@
tree_oak_branch_left,\
tree_oak_branch_right,/
tree_oak_stem,█
tree_pine_top,⋀
tree_pine_side_left,/
tree_pine_side_right,\
tree_pine_centre,^
tree_pine_stem,█
water_wave1,~
water_wave2,≈
water_wave3,≋